name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.2' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/encodeous/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build -c Release
    - name: Create the package
      run: dotnet pack -c Release
    - name: Publish the package to GPR
      run: dotnet nuget push bin/Release/*.nupkg
